### ISSUE TITLE
Fixing spillover of toot status

### ISSUE THREAD

**Issue by bmp** [rougier/mastodon-alt#14]
I had some spillover of the toot status line (both in full screen and when Emacs is resized as shown in the two screenshots below:

![Toot_status_spillover_resizedWindow](https://user-images.githubusercontent.com/1095177/236697934-404fbd9c-b320-49db-a7b4-3da8544674c8.png)
![Toot_Status_spillover_fullscreen](https://user-images.githubusercontent.com/1095177/236697935-b19376a9-e09a-4694-b81b-289a4273460c.png)

I fixed it by changing the value in the [mastodon-alt-tl--toot-status ](https://github.com/rougier/mastodon-alt/blob/6390c5c2ad9a32ace971cd3627890b6728d54dbe/mastodon-alt.el#L526) function from 2 to 6 in my case. The status now aligns with the time above the toot.

**Comment by rougier** [comment]
Thanks for the report. Not sure why value 6 would work. Do you have fringes and/or margins?

**Comment by bmp** [comment]
Nope, only git gutter enabled.

**Comment by rougier** [comment]
What is git gutter exactly?

**Comment by bmp** [comment]
https://github.com/emacsorphanage/git-gutter shows the git status

**Comment by bmp** [comment]
Moved to [diff-hl](https://github.com/dgutov/diff-hl) and the issue has gone away without the hack now. Please do feel free to mark the issue as closed now.
