### ISSUE TITLE
Toggle folding of content warnings by default?

### ISSUE THREAD

**Issue by deen1** [rougier/mastodon-alt#15]
The default layout from `mastodon.el` appears to respect my preference for toots which come with a content warning, which is to hide the content until I toggle the warning by hitting `c`.

![2023-06-02-232601_1896x225_scrot](https://github.com/rougier/mastodon-alt/assets/1893566/350c6d8d-6c76-49a3-b2ea-39fe5a8c84bf)

However, switching to `mastodon-alt` results in all content warning "boxes" are shown by default, and I have to hide them by toggling, which sort of defeats the point of the warning. 

![2023-06-02-232119_1897x331_scrot](https://github.com/rougier/mastodon-alt/assets/1893566/5871ea6f-90e6-49c3-8903-9073df67de63)

Is there a variable/setting I can use to change the default behavior for content warnings/boxes in `mastodon-alt`?

**Comment by mooseyboots** [comment]
`(mastodon-profile--get-preferences-pref 'reading:expand:spoilers)` returns the desired value.

the test in `mastodon.el` is at https://codeberg.org/martianh/mastodon.el/src/commit/dfc40c0bc2c8f1653ca71335b6ad99230f38067e/lisp/mastodon-tl.el#L1028

**Comment by deen1** [comment]
@mooseyboots  Thanks -- this evaluates to `:json-false`, which I believe is the correct value. So I guess the next step is to use this condition to re-implement this test in `mastodon-alt`.

**Comment by rougier** [comment]
Thanks, I'll look into that or @deen1, do you want to make a PR? I think thie [line](https://github.com/rougier/mastodon-alt/blob/master/mastodon-alt.el#L648) needs to be modified.

**Comment by deen1** [comment]
@rougier  I tried to adjust the line by doing

```
            (mastodon-alt-tl--folding-box content
                                          mastodon-alt-tl-box-width
					  nil
					  (eq :json-false
						      (condition-case nil
							  (mastodon-profile--get-preferences-pref
							   'reading:expand:spoilers)
							(error nil)))
                                          mastodon-alt-tl-box-prefix)
```

but this just seems to break boxes for boosts rather than fix CWs -- is it this [line](https://github.com/rougier/mastodon-alt/blob/67d747711613d29b1c7877135a331f823690bb4c/mastodon-alt.el#L639) that needs to be fixed?

*EDIT:* Yes, that seemed to do the trick for me. Maybe the pull request #16 will work for everyone?

**Comment by rougier** [comment]
Just merged it!
